<?php

function tt_form_stanford_r25_reservation_alter(&$form, &$form_state, $form_id) {
  $form['stanford_r25_booking_reason']['#title'] = 'Event Title';
  $form['stanford_r25_booking_headcount']['#type'] = 'hidden';
  $form['stanford_r25_booking_headcount']['#value'] = 1;
  $form['submit']['#prefix'] = '<span>By clicking the Reserve button, I confirm that I have read and agree to the <a href="https://uit.stanford.edu/service/techtraining/facilityrentalpolicy">Facility Rental Policy</a></span><br />';
  $form['stanford_r25_booking_attr144']['#suffix'] = '<div class="form-item"><span class="description">E.g., 1234567-123-ABCDE (Case sensitive)</span></div>';
  $form['stanford_r25_booking_attr182']['#suffix'] = '<div class="form-item"><span class="description">E.g., Mac or PC</span></div>';
  $form['stanford_r25_booking_attr182']['#maxlength'] = 80;
  array_unshift($form['#validate'], 'tt_stanford_r25_pta_validate');
  $form['#submit'][] = 'tt_stanford_r25_reservation_submit';
}

// Remove the Headcount: 2 (which is hard-coded) from the tool tip
function tt_stanford_r25_contact_alter(&$data) {
  $data = str_replace('<br />Headcount: 2', '', $data);
  $data = str_replace('<br />Headcount:', '', $data);
}

function tt_stanford_r25_pta_validate($form, &$form_state) {
  if (preg_match('/;/', $form_state['values']['stanford_r25_booking_reason'])) {
      form_set_error('stanford_r25_booking_reason', t('Please do not include the ; character in the title of the event.'));
  }

  $form_state['values']['stanford_r25_booking_attr144'] = trim($form_state['values']['stanford_r25_booking_attr144']);
  if (!(preg_match('/^(\d{7})\-(\d.*)\-([A-Z]{5})$/', $form_state['values']['stanford_r25_booking_attr144']))) {
      form_set_error('stanford_r25_booking_attr144', t('Invalid PTA Format. The correct format is Project-Task-Award (e.g. 1234567-123-ABCDE)'));
  }
}

// Remove the Sender and other headers so emails only appear to come from Tech Training, and not the website admins.
function tt_mail_alter(&$message) {
  if (preg_match('/stanford_r25/', $message['id'])) { 
    unset($message['headers']['Sender']);
    unset($message['headers']['Errors-To']);
    unset($message['headers']['Return-Path']);
  }
}

function tt_stanford_r25_reservation_submit($form, &$form_state) {

  dpm($form_state);
  
  // look for what's in the drupal_mail function
  // look for postprocess_booking in $form_state
  if (!empty($form_state['storage']['stanford_r25_postprocess']['room'])) {
   
    global $base_url;
    global $user;
    $date = DateTime::createFromFormat(DATE_W3C, $form_state['storage']['stanford_r25_postprocess']['dates']['start']);
    $res_usermail = $user->mail;
    $res_username = $user->name;
    $subject = 'Rental Receipt - ' . $form_state['storage']['stanford_r25_postprocess']['room']['display_name'] . ' - ' . $form_state['values']['stanford_r25_booking_reason'];
    $body[] = 'Hi ' . $res_username . ',';
    $body[] = 'Thank you for your reservation of ' . $form_state['storage']['stanford_r25_postprocess']['room']['display_name'] . ' on ' . $date->format("l, F j, Y g:i a") . '.';
    $body[] = 'If this is your first time renting a Technology Training facility, we will be in touch to schedule a mandatory orientation of the room. The goal of the orientation is to provide you with essential information (such as the door code) to ensure your event is a success.';
    $body[] = 'You can view or cancel your reservation at: ' . $base_url . '/r25/' . $form_state['storage']['stanford_r25_postprocess']['room']['machine_name'] . '/calendar';
    $body[] = 'Please read our facility rental policy at: https://uit.stanford.edu/service/facilityrentals/policy';
    $body[] = 'For any questions, please contact us at tt-questions@lists.stanford.edu.';
    $body[] = 'Thank you,';
    $body[] = 'University IT Technology Training<br>http://techtraining.stanford.edu';
    
    /*$body[] = "Room: " . $form_state['storage']['stanford_r25_postprocess']['room']['display_name'];
    $body[] = "Date: " . $date->format("l, F j, Y g:i a");
    $duration = (intval($form_state['values']['stanford_r25_booking_duration']) * 30) + 30;
      if ($duration > 120) {
        $body[] = 'Duration: ' . $duration / 60 . ' hours';
      }
      else {
        $body[] = 'Duration: ' . $duration . ' minutes';
      }
    $body[] = "Event Title: " . $form_state['values']['stanford_r25_booking_reason'];
    $body[] = "Requested by: " . $res_username . " " . $res_usermail;
    if ($form_state['storage']['stanford_r25_postprocess']['est_charge'] > 0) {
      $body[] = "Estimated Fee: $" . $form_state['storage']['stanford_r25_postprocess']['est_charge'];
    }
    dpm($body);
*/
    $params = array(
      'body' => $body,
      'subject' => $subject
    ); 
    drupal_mail('stanford_r25', 'receipt', $res_usermail, language_default(), $params, variable_get('stanford_r25_from_email', variable_get('site_mail')));
  }
  
}